const data =[{
    id:1,
    name:"Aswin",
    mail:"aswinedassery@gmail.com",
    password:"Aswines@123",
    age:24,
    place:'Thrissur',
    img:"5.jpeg",
    progress:10,
    bg:"success"
},{
    id:2,
    name:"Abhilash",
    mail:"abhimodiyil197@gmail.com",
    age:29.5,
    place:'Pathanamthitta',
    img:"3.jpeg",
    progress:20,
    bg:"info"
},{
    id:3,
    name:"Sagar",
    mail:"sagarsam606@gmail.com",
    age:20,
    place:'Kottayam',
    img:"1.jpeg",
    progress:30,
    bg:"warning"
},{
    id:4,
    name:"Priyesh",
    age:52,
    place:'Kollam',
    img:"2.jpeg",
    progress:40,
    bg:"success"
},
{
    id:5,
    name:"Adal",
    age:23,
    place:'Chalakudi',
    img:"4.jpeg",
    progress:50,
    bg:"success"
}]

module.exports = data